### ISSUE TITLE
Crunchbase API v3 is out!

### ISSUE THREAD

**Issue by ngzhian** [ngzhian/pycrunchbase#10]
http://data.crunchbase.com/v3/docs

 - [x] upgrade url
 - [x] make sure built urls still work fine
 - [x] update known relationships and known properties
 - [x] add new supported features to pycrunchbase, e.g. http://data.crunchbase.com/v3/docs/peoplepermalinkrelationship-name
 - [x] ~~According to the docs http://data.crunchbase.com/v3/docs/address Address have `city_path` and `region_path`, but an actual query returns `city_web_path` and `region_web_path`~~ they fixed it!
 - [x] new location entity
 - [x] new category entity
 - [x] ~~Remove the Relationship class, use a builder to build nodes / list of nodes instead~~

All dev will be done on the [apiv3](https://github.com/ngzhian/pycrunchbase/tree/apiv3) branch.

**Comment by ngzhian** [comment]
Can probably work work on using trust_code to parse dates too

**Comment by ngzhian** [comment]
support person -> degrees relationship

**Comment by ngzhian** [comment]
new category entity

**Comment by ngzhian** [comment]
new location entity

**Comment by ngzhian** [comment]
According to the docs http://data.crunchbase.com/v3/docs/address Address have `city_path` and `region_path`, but an actual query returns `city_web_path` and `region_web_path`

**Comment by dustinfarris** [comment]
Were you able to use your existing user key for the new API version?  I seem to be having trouble with mine.

**Comment by ngzhian** [comment]
@dustinfarris so they basically 'revoked' all existing api keys, you have to fill up the form here http://data.crunchbase.com/v3/page/accessing-the-dataset to request for a key. In the form you can check the box that says you are an existing user, and can enter your current api key. They will then try to authorize the same api key, that's what I did.

**Comment by ngzhian** [comment]
this is pushed to master and up on pypi!
