### ISSUE TITLE
Keep getting API Authorization / Rate Limit Error

### ISSUE THREAD

**Issue by kevinzzz007** [ngzhian/pycrunchbase#12]
I just got my API key so this shouldn't happen, but it does.  The data retrieved is good.  For example, when I run the following code:

    github = cb.organization('google')
    print github
    funding_rounds_summary = github.funding_rounds
    print funding_rounds_summary

I get 

    Organization: Google
    funding_rounds Total: 2 https://api.crunchbase.com/v/3/organizations/google/funding_rounds

Any ideas why?

**Comment by ngzhian** [comment]
Hm, @kevinzzz007 from the output you pasted I don't see any errors, where do you see the API authorization/ rate limit error?

**Comment by kevinzzz007** [comment]
@ngzhian hi if you click on the link, you will see the error

**Comment by ngzhian** [comment]
@kevinzzz007 that link given is the API link, you're supposed to call thank link and pass in your API Key as a parameter in the URL. To use pycrunchbase to get that data, you can do
```python
cb.more(funding_rounds[0].uuid)
```

**Comment by kevinzzz007** [comment]
I see, thank you so much!

**Comment by ngzhian** [comment]
You're welcome, @kevinzzz007 . closing this issue.
