### ISSUE TITLE
News link on crunchbase page but org.news returns NoneRelationship

### ISSUE THREAD

**Issue by kevinzzz007** [ngzhian/pycrunchbase#14]
Hi there, so I have this code:

org = cb.organization('ARCH-Venture-Partners')
in_the_news = org.news

If you go the arch-venture-partners page(https://www.crunchbase.com/organization/arch-venture-partners#x), you will find that there are links to articles, but when I print out in_the_news, it gives me NoneRelationship, has anyone encountered this before?

**Comment by ngzhian** [comment]
@kevinzzz007 thanks for reporting this, I got the exact same result as you. This may be an error on the API part. I took a look at the response from the API and the `news` field is missing from the response. I even tried it out on their API explorer [here](http://data.crunchbase.com/v3/docs/organizationpermalink), and again the `news` field wasn't returned.
Can you go to their [API explorer](http://data.crunchbase.com/v3/docs/organizationpermalink) and try it? If you cannot get the `news` field as well, this is probably an issue on crunchbase side, and we can then bring it up to them.

**Comment by kevinzzz007** [comment]
@ngzhian Thanks for checking this out.  I got the same thing, with on news field... how can we bring up this issue to them?

**Comment by ngzhian** [comment]
@kevinzzz007 I usually email data@crunchbase.com and point out the issues to them. I think will be good to email them and tell them what the discrepancy is. If you want you can cc me in the email as well: ngzhian@gmail.com

**Comment by kevinzzz007** [comment]
Done!

**Comment by ngzhian** [comment]
I tried this again on version v0.3.6 and things work fine. The call is
`org = cb.organization('arch-venture-partners')`, note the name of the organization has to be all lowercase. 
Therefore I shall close this issue. Happy to help if anything similar pops up again @kevinzzz007 , thanks!
