### ISSUE TITLE
Can't find people related info

### ISSUE THREAD

**Issue by kevinzzz007** [ngzhian/pycrunchbase#16]
I have the following code to find person related info:

    cb = pycrunchbase.CrunchBase('api-key-here')

    print cb.person('ben-horowitz')

it returns

    AttributeError: 'list' object has no attribute 'get'

I was wondering if there is anther way to access person level information...

**Comment by ngzhian** [comment]
This should be an issue that was fixed in the latest version of v0.3.1, can you please check your version?

https://pypi.python.org/pypi/pycrunchbase/
