### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by ruphus13** [ngzhian/pycrunchbase#17]
Hi - not sure if I'm doing something incorrect here.

Tried the example code in the docs. 
github = cb.organization('github')

The URL from the code resolves to: 
https://api.crunchbase.com/v/3/organizations/github?user_key=<API_KEY>

This results in a 401 error.

However, on the crunchbase site, this URL should be:
https://api.crunchbase.com/v/3/organizations?name=github&user_key=<API_KEY>

Looks like the name now needs to be a URL parameter.

I've just started playing with the lib, so I'm guessing this is a result of crunchbase changing around their services?

**Comment by ngzhian** [comment]
Hi @ruphus13 , thanks for the report. I've just tried the example code and it works for me. Did you create the `CrunchBase` object with your API key? For example:

```python
cb = CrunchBase('YOUR_API_KEY')
cb.organization('github')
```
You might want to go to the [API playground on CrunchBase](http://data.crunchbase.com/v3/docs/organizationpermalink) to verify that our API key is working.

As a side note, the 2 URLs do different thing:
https://api.crunchbase.com/v/3/organizations/github?user_key= gets an organization by a permalink
https://api.crunchbase.com/v/3/organizations?name=github&user_key= looks up organizations by a name

**Comment by ruphus13** [comment]
Hi - I apologize.

You are right.

The first URL doesn’t work for me even via the web interface.  The second one does. (See attached images for both)

I’m guessing this is a problem with my API key… Will contact CB.

I just went to the first interface and tried it out, and got it to work, so I didn’t check the :permalink URL, and I assumed the API was incorrect.

Would you like me to update you on what I find out from CB?

Thanks, and apologies.

**Comment by ngzhian** [comment]
Oh @ruphus13 no worries about this at all! Yes please do close this issue with a comment on how this was resolved, will be helpful for other people who face a similar problem in the future :)

**Comment by ngzhian** [comment]
It has been a while since I got feedback on this, chances are it was a thing about the API key, so I shall resolve this, let me know if I can help with anything else @ruphus13 , thanks!
