### ISSUE TITLE
Problems when we obtain stock_exchange attribute of organiziation.

### ISSUE THREAD

**Issue by acosgaya** [ngzhian/pycrunchbase#19]
Hi!

I'm trying to obtain stock_exchange attribute of organization, but failed.

Example of code:

```
cb = CrunchBase('API_KEY')
organization = cb.organization('pmfg')
print organization.stock_exchange
```

And the error is:

```
AttributeError: 'Organization' object has no attribute 'stock_exchange'
```

Thank you so much.

**Comment by ngzhian** [comment]
@acosgaya weird, thought i just fixed it in the latest release, can you just make sure that your version of pycrunchbase is 0.3.2? Otherwise I'll look at it later today, thanks for pointing out the bug!

**Comment by acosgaya** [comment]
Hi,

The crunchbase version is:

```
>> pip show pycrunchbase
---
Name: pycrunchbase
Version: 0.3.2
Location: c:\anaconda\lib\site-packages
Requires: requests, six
```
Best regards,

**Comment by acosgaya** [comment]
Hi, something new about this issue?

Thank you.

**Comment by ngzhian** [comment]
Hi @acosgaya, thanks for your patience, this has been fixed in the latest commit, I have pushed this new [version 0.3.3 up to pypi](https://pypi.python.org/pypi/pycrunchbase/), please install it and try it, it should work fine, now. :)

**Comment by acosgaya** [comment]
Hi @ngzhian, thank you very much, the issue is fixed.
