### ISSUE TITLE
Example code not working, 'Person' object has no attribute 'cbid'

### ISSUE THREAD

**Issue by sanazb** [ngzhian/pycrunchbase#20]
I tried the following example code (from [here](https://pycrunchbase.readthedocs.org/en/latest/usage.html))
```python
import pycrunchbase
cb = pycrunchbase.CrunchBase(API_KEY)
github = cb.organization('github')
who_started_github = github.founders
a_founder = who_started_github[0]
cb.person(a_founder.cbid)
```

This results in the following error:
```python
'Person' object has no attribute 'cbid'
```

**Comment by ngzhian** [comment]
@sanazb this is fixed in the latest version here http://pycrunchbase.readthedocs.org/en/latest/usage.html, thanks for the report!

**Comment by ngzhian** [comment]
It's been a while, so assume this is fixed!
