### ISSUE TITLE
Percent encode reserved URL chars

### ISSUE THREAD

**Issue by bofia** [ngzhian/pycrunchbase#26]
Calling Crunchbase.organizations('Attencia & Penina Mezei') results in the request url: 'https://api.crunchbase.com/v/3/organizations?name=Attencia%20&%20Penina%20Mezei' and causes a 400 error because the & should be URI encoded to %26

**Comment by ngzhian** [comment]
Hi @bofia, thanks for using this library and reporting this bug!
Would you like to make a PR for this bug. The relevant code is at  https://github.com/ngzhian/pycrunchbase/blob/master/src/pycrunchbase/pycrunchbase.py#L209
(I am not actively using this library now so to fix this and push a new version so I can only do this when I'm more available)

**Comment by bofia** [comment]
thanks @ngzhian! its quite useful here at equityzen

**Comment by ngzhian** [comment]
Pushed as v0.3.8 :) https://pypi.python.org/pypi/pycrunchbase/
Thanks for your contribution!
