### ISSUE TITLE
pip install problem?

### ISSUE THREAD

**Issue by asifm** [ngzhian/pycrunchbase#4]
pip shows it's installing version 0.2, but after installation when I import the library and check for its version, it shows 0.1
![image](https://cloud.githubusercontent.com/assets/3958387/6316818/955c9238-ba02-11e4-8d79-207c7b6c08c4.png)

**Comment by ngzhian** [comment]
ahh good catch, the right version is installed, just that the [version in the file](https://github.com/ngzhian/pycrunchbase/blob/master/src/pycrunchbase/__init__.py) is not updated. This is fixed, you should see v0.2.1 reflected correctly in all places :+1:
