### ISSUE TITLE
Accessing 'sub_organization' & 'websites' from organization

### ISSUE THREAD

**Issue by spgenot** [ngzhian/pycrunchbase#9]
Hey,
Unfortunately I am not able to simply access these fields. 
I get : AttributeError: 'Organization' object has no attribute 'sub_organizations', same for websites.
I think the problem comes from KNOW_RELATIONSHIPS, when I print it, the last field is : 
'sub_organizationwebsites' and not 'sub_organization','websites'.
I'm using version 0.2.6

**Comment by ngzhian** [comment]
@spgenot this was a bug on my side, missed a comma :( This has been fixed in v0.2.7, and has been pushed to pypi. Thanks for reporting this and figuring out what's wrong! :+1:
